#!/bin/bash
#Модификация перехваченных сигналов.

trap "echo 'Ctrl-C перехвачен.'" SIGINT
count=1
while [ $count -le 5 ]
do
	echo "Цикл #$count"
	sleep 1
	count=$(( $count + 1 ))
done
trap "echo ' Я модифицировал перехват!'" SIGINT
count=1
while [ $count -le 5 ]
do
	echo "Второй цикл #$count"
	sleep 1
	count=$(( $count + 1 ))
done