#!/bin/bash
#Перехват сигналов.

trap "echo ' Перехвачен сигнал Ctr1-C'" SIGINT
echo Это тестовый скрипт.
count=1
while [ $count -le 10 ]
	do
		echo "Цикл #$count"
		sleep 1
		count=$(( $count + 1 ))
	done 
	
	