#!/bin/bash
#Обход файлов, содержащихся в директории.

for file in /home/dmitry/*
do
	if [ -d "$file" ]
	then
		echo "$file является директорией."
	elif [ -f "$file" ]
	then
		echo "$file является файлом."
	fi
done

