#!/bin/bash
#Неправильное использование функций.

count=1
while [ $count -le 3 ]
do
	myfunc
	count=$(( $count + 1 ))
done
echo "Это конец цикла"
function myfunc {
	echo "Это пример использования функции"
}
echo "Конец скрипта"