#!/bin/bash
#Аргументы функций.

function addnum {
if [ $# -eq 0 ] || [ $# -gt 2 ]
	then
		echo -1
	elif [ $# -eq 1 ]
		then
		echo $(( $1 + $1 ))
		else
		echo $(( $1 + $2 ))
fi
}
echo -n "Сложение 10 и 15: "
value=$(addnum 10 15)
echo $value
echo -n "Сложение с одним параметром: "
value=$(addnum 10)
echo $value
echo -n "Сложение без параметров: "
value=$(addnum)
echo $value
echo -n "Сложение с тремя параметрами: "
value=$(addnum 10 15 20)
echo $value