#!/bin/bash
#Нужно объявить функции вместе с параметрами,
#чтобы функция прочитала их.

function myfunc {
	echo $(( $1 + $2 ))
}
if [ $# -eq 2 ]
	then
		value=$(myfunc $1 $2)
		echo "Результат = $value"
	else
		echo "Использование: myfunc a b"
fi